services:

  resettlement-passport-db:
    image: postgres
    networks:
      - hmpps
    container_name: resettlement-passport-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=resettlement-passport
      - POSTGRES_USER=resettlement-passport
      - POSTGRES_DB=resettlement-passport

  wiremock:
    image: wiremock/wiremock
    command: "--no-request-journal --global-response-templating --verbose"
    networks:
      - hmpps
    container_name: rp-api-wiremock
    ports:
      - "9193:8080"
    volumes:
      - "./helm_deploy/hmpps-resettlement-passport-api/files/stubs:/home/wiremock:ro"

  redis:
    image: 'redis:7.0'
    networks:
      - hmpps
    container_name: redis-be
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6380:6379'

  localstack:
    image: localstack/localstack:stable
    networks:
      - hmpps
    container_name: localstack-resettlement-passport-api
    ports:
      - "4566:4566"
  clamav:
    image: ghcr.io/ministryofjustice/hmpps-clamav-freshclammed:latest
    networks:
      - hmpps
    container_name: clamav
    ports:
      - "3310:3310"

networks:
  hmpps:
