version: "3"
services:

  resettlement-passport-db:
    image: postgres
    networks:
      - hmpps
    container_name: resettlement-passport-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=resettlement-passport
      - POSTGRES_USER=resettlement-passport
      - POSTGRES_DB=resettlement-passport

  wiremock:
    image: wiremock/wiremock
    command: "--no-request-journal --global-response-templating --verbose"
    networks:
      - hmpps
    container_name: rp-api-wiremock
    ports:
      - "9093:8080"
    volumes:
      - "./helm_deploy/hmpps-resettlement-passport-api/files/stubs:/home/wiremock:ro"

networks:
  hmpps:
