version: "3"
services:
  hmpps-resettlement-passport-api:
    build:
      context: .
    networks:
      - hmpps
    container_name: hmpps-resettlement-passport-api
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - API_BASE_URL_OAUTH=https://sign-in-dev.hmpps.service.justice.gov.uk/auth
      - SPRING_DATASOURCE_URL=jdbc:postgresql://resettlement-passport-db:5432/resettlement-passport?sslmode=prefer
      - SPRING_FLYWAY_URL=jdbc:postgresql://resettlement-passport-db:5432/resettlement-passport?sslmode=prefer
      - RESETTLEMENT_PASSPORT_API_CLIENT_ID=${RESETTLEMENT_PASSPORT_API_CLIENT_ID}
      - RESETTLEMENT_PASSPORT_API_CLIENT_SECRET=${RESETTLEMENT_PASSPORT_API_CLIENT_SECRET}
      - API_BASE_URL_PRISON_REGISTER=http://prison-register-api-stub:8080
      - API_BASE_URL_OFFENDER_SEARCH=http://prisoner-offender-search-api-stub:8080
      - API_BASE_URL_CVL=http://cvl-stub:8080
      - API_BASE_URL_ARN=http://arn-api-stub:8080
      - API_BASE_URL_PRISON=http://prison-api-stub:8080
      - API_BASE_URL_RESETTLEMENT-PASSPORT-DELIUS=http://resettlement-passport-and-delius-api-stub:8080

networks:
  hmpps:
