version: "3"
services:
  localstack:
    image: localstack/localstack:0.14.0
    networks:
      - hmpps
    container_name: localstack-resettlement-passport-api
    ports:
      - "4566-4597:4566-4597"
      - "8999:8080"
    environment:
      - SERVICES=sns,sqs
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_EXECUTION_ENV=True
      - DEFAULT_REGION=eu-west-2
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  resettlement-passport-db:
    image: postgres
    networks:
      - hmpps
    container_name: resettlement-passport-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=resettlement-passport
      - POSTGRES_USER=resettlement-passport
      - POSTGRES_DB=resettlement-passport

  cvl-stub:
    image: wiremock/wiremock
    command: "--global-response-templating --verbose"
    networks:
      - hmpps
    container_name: cvl-api-stub
    ports:
      - "8081:8080"
    volumes:
      - "./helm_deploy/hmpps-resettlement-passport-api/files/stubs/cvl-api:/home/wiremock:ro"

  community-api-stub:
    image: wiremock/wiremock
    command: "--global-response-templating --verbose"
    networks:
      - hmpps
    container_name: community-api-stub
    ports:
      - "8082:8080"
    volumes:
      - "./helm_deploy/hmpps-resettlement-passport-api/files/stubs/community-api:/home/wiremock:ro"

  prison-register-api-stub:
    image: wiremock/wiremock
    command: "--global-response-templating --verbose"
    networks:
      - hmpps
    container_name: prison-register-api-stub
    ports:
      - "8083:8080"
    volumes:
      - "./helm_deploy/hmpps-resettlement-passport-api/files/stubs/prison-register-api:/home/wiremock:ro"

  arn-api-stub:
    image: wiremock/wiremock
    command: "--global-response-templating --verbose"
    networks:
      - hmpps
    container_name: arn-api-stub
    ports:
      - "8084:8080"
    volumes:
      - "./helm_deploy/hmpps-resettlement-passport-api/files/stubs/arn-api:/home/wiremock:ro"

  prisoner-offender-search-api-stub:
    image: wiremock/wiremock
    command: "--global-response-templating --verbose"
    networks:
      - hmpps
    container_name: prisoner-offender-search-api-stub
    ports:
      - "8085:8080"
    volumes:
      - "./helm_deploy/hmpps-resettlement-passport-api/files/stubs/prisoner-offender-search-api:/home/wiremock:ro"

networks:
  hmpps: