include:
  - docker-compose-local.yml
services:
  hmpps-resettlement-passport-api:
    build:
      context: .

    networks:
      - hmpps
    container_name: hmpps-resettlement-passport-api
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - API_BASE_URL_OAUTH=https://sign-in-dev.hmpps.service.justice.gov.uk/auth
      - SPRING_DATASOURCE_URL=jdbc:postgresql://resettlement-passport-db:5432/resettlement-passport?sslmode=prefer
      - SPRING_FLYWAY_URL=jdbc:postgresql://resettlement-passport-db:5432/resettlement-passport?sslmode=prefer
      - RESETTLEMENT_PASSPORT_API_CLIENT_ID=${RESETTLEMENT_PASSPORT_API_CLIENT_ID}
      - RESETTLEMENT_PASSPORT_API_CLIENT_SECRET=${RESETTLEMENT_PASSPORT_API_CLIENT_SECRET}
      - API_BASE_URL_PRISON_REGISTER=http://wiremock:8080/prison-register-api
      - API_BASE_URL_PRISONER_SEARCH=http://wiremock:8080/prisoner-search-api
      - API_BASE_URL_CVL=http://wiremock:8080/cvl-api
      - API_BASE_URL_ARN=http://wiremock:8080/arn-api
      - API_BASE_URL_PRISON=http://wiremock:8080/prison-api
      - API_BASE_URL_RESETTLEMENT-PASSPORT-DELIUS=http://wiremock:8080/resettlement-passport-and-delius-api
      - API_BASE_URL_EDUCATION-EMPLOYMENT=http://wiremock:8080/education-employment-api
      - API_BASE_URL_CIAG=http://wiremock:8080/ciag-api
      - API_BASE_URL_INTERVENTIONS-SERVICE=http://wiremock:8080/interventions-service-api
      - API_BASE_URL_pop-user-service=http://wiremock:8080/pop-user-api
      - API_BASE_URL_CASE-NOTES=https://dev.offender-case-notes.service.justice.gov.uk
      - API_BASE_URL_KEY-WORKER=http://wiremock:8080/key-wprler-api-
      - API_BASE_URL_ALLOCATION-MANAGER=http://wiremock:8080/allocation-manager-api
      - SCHEDULE_EXPRESSION_CUSTOM-METRICS=0 0/15 * * * ?
      - SCHEDULE_EXPRESSION_RELEASED-DAY-METRICS=0 0 2 * * *
      - SCHEDULE_EXPRESSION_RECONCILE-RELEASE-DATES=0 0 2 * * *
      - SCHEDULE_EXPRESSION_DELETE-EXPIRED-OTP=0 0 3 * * *

networks:
  hmpps:
