server:
  shutdown: immediate

# Base URLs of downstream APIs. Switch the comments to use the real dev services instead of the test stubs
api:
  base:
    url:
      oauth: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
      #oauth: http://localhost:9090/auth
      prison-register: http://localhost:8083
      #prison-register: https://prison-register-dev.hmpps.service.justice.gov.uk
      #offender-search: https://prisoner-offender-search-dev.prison.service.justice.gov.uk
      offender-search: http://localhost:8085
      cvl: http://localhost:8081
      #cvl: https://create-and-vary-a-licence-api-dev.hmpps.service.justice.gov.uk
      community: http://localhost:8082
      #community: https://community-api.test.probation.service.justice.gov.uk
      arn: http://localhost:8084
      #arn: https://assess-risks-and-needs-dev.hmpps.service.justice.gov.uk
      prison: http://localhost:8086
      #prison: https://api-dev.prison.service.justice.gov.uk
      offender-case-notes: https://dev.offender-case-notes.service.justice.gov.uk

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0
spring:
  devtools:
    add-properties: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    url: 'jdbc:postgresql://localhost:5432/resettlement-passport?sslmode=prefer'
    username: resettlement-passport
    password: resettlement-passport
    hikari:
      pool-name: Hmpps-Resettlement-Passport
      connectionTimeout: 1000
      validationTimeout: 500

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/resettlement-passport?sslmode=prefer
    user: resettlement-passport
    password: resettlement-passport

  feature-toggles:
    afine: true