server:
  shutdown: immediate

api:
  base:
    url:
      oauth: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
      #oauth: http://localhost:9090/auth
      prison: https://prison-register-dev.hmpps.service.justice.gov.uk
      #prison: http://localhost:8082
      offender-search: https://prisoner-offender-search-dev.prison.service.justice.gov.uk
      #offender-search: http://localhost:8083
      cvl: https://create-and-vary-a-licence-api-dev.hmpps.service.justice.gov.uk
      community: https://community-api.test.probation.service.justice.gov.uk

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0
spring:
  devtools:
    add-properties: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

  datasource:
    url: 'jdbc:postgresql://localhost:5432/resettlement-passport?sslmode=prefer'
    username: resettlement-passport
    password: resettlement-passport
    hikari:
      pool-name: Hmpps-Resettlement-Passport
      connectionTimeout: 1000
      validationTimeout: 500

  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/resettlement-passport?sslmode=prefer
    user: resettlement-passport
    password: resettlement-passport

  feature-toggles:
    afine: true