generic-service:
  nameOverride: hmpps-resettlement-passport-api

  replicaCount: 5

  image:
    repository: quay.io/hmpps/hmpps-resettlement-passport-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: resettlement-passport-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    SCHEDULE_EXPRESSION_CUSTOM-METRICS: 0 0/15 * * * ?
    SCHEDULE_EXPRESSION_RELEASE-DAY-METRICS: 0 0 4 * * *
    SCHEDULE_EXPRESSION_RECONCILE-RELEASE-DATES: 0 0 2 * * *
    SCHEDULE_EXPRESSION_DELETE-EXPIRED-OTP: 0 0 3 * * *


  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-resettlement-passport-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      RESETTLEMENT_PASSPORT_API_CLIENT_ID: "SYSTEM_CLIENT_ID"
      RESETTLEMENT_PASSPORT_API_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    rds-postgresql-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      SPRING_FLYWAY_USER: "database_username"
      SPRING_FLYWAY_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
    backend-elasticache-redis:
      SPRING_DATA_REDIS_HOST: "primary_endpoint_address"
      SPRING_DATA_REDIS_PASSWORD: "auth_token"

  allowlist:
    groups:
      - internal

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /prometheus
    metricsPort: http

generic-prometheus-alerts:
  targetApplication: hmpps-resettlement-passport-api

# Whether to deploy the stubs
# Override in values-dev.yaml
# Also update the environment variables to point the application to the mocked services (on port 80) e.g. http://cvl-stub-api
deploy_stubs: false
