---
generic-service:
  nameOverride: hmpps-resettlement-passport-api

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-resettlement-passport-api
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: resettlement-passport-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-resettlement-passport-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      RESETTLEMENT_PASSPORT_API_CLIENT_ID: "SYSTEM_CLIENT_ID"
      RESETTLEMENT_PASSPORT_API_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    rds-postgresql-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      SPRING_FLYWAY_USER: "database_username"
      SPRING_FLYWAY_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live-1: "35.178.209.113/32"
    cloudplatform-live-2: "3.8.51.207/32"
    cloudplatform-live-3: "35.177.252.54/32"

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /prometheus
    metricsPort: http

generic-prometheus-alerts:
  targetApplication: hmpps-resettlement-passport-api

# List of stubs to deploy (for testing only). Add wiremock mappings/__files into files/stubs/<stub-name>/
# Override in values-dev.yaml
# Also update the environment variables to point the application to the mocked services (on port 80) e.g. http://cvl-stub-api
deploy_stubs: []
