generic-service:
  nameOverride: hmpps-resettlement-passport-api
  resources:
    requests:
      memory: 1G
    limits:
      memory: 2G
  replicaCount: 5

  image:
    repository: quay.io/hmpps/hmpps-resettlement-passport-api
    tag: app_version # override at deployment time
    port: 8080

  volumes:
    - name: conversion
      emptyDir:
        sizeLimit: 2Gi

  volumeMounts:
    - mountPath: /conversion-tmp
      name: conversion

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: resettlement-passport-api-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location ~ (/queue-admin/retry-all-dlqs|/retry-failed-delius-case-notes) {
          deny all;
          return 401;
        }



  startupProbe:
    httpGet:
      path: /health/liveness
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 30

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash,offender-events"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    SCHEDULE_EXPRESSION_CUSTOM-METRICS: 0 0/15 * * * ?
    SCHEDULE_EXPRESSION_RELEASE-DAY-METRICS: 0 0 4 * * *
    SCHEDULE_EXPRESSION_RECONCILE-RELEASE-DATES: 0 0 2 * * *
    SCHEDULE_EXPRESSION_DELETE-EXPIRED-OTP: 0 0 3 * * *
    CLAMAV_HOSTNAME: hmpps-resettlement-passport-api-clamav
    CLAMAV_PORT: 3310
    DOC_CONVERSION_TEMP_DIR_PATH: /conversion-tmp

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-resettlement-passport-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      RESETTLEMENT_PASSPORT_API_CLIENT_ID: "SYSTEM_CLIENT_ID"
      RESETTLEMENT_PASSPORT_API_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    rds-postgresql-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      SPRING_FLYWAY_USER: "database_username"
      SPRING_FLYWAY_PASSWORD: "database_password"
      DATABASE_NAME: "database_name"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
    backend-elasticache-redis:
      SPRING_DATA_REDIS_HOST: "primary_endpoint_address"
      SPRING_DATA_REDIS_PASSWORD: "auth_token"
    sqs-prisoner-event-queue-secret:
      OFFENDER_EVENT_QUEUE_NAME: "sqs_queue_name"
      OFFENDER_EVENT_DLQ_NAME: "sqs_dlq_queue_name"
    s3-bucket-document-storage:
      S3_DOCUMENT_BUCKET_NAME: bucket_name

  allowlist:
    groups:
      - internal

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /prometheus
    metricsPort: http

generic-prometheus-alerts:
  targetApplication: hmpps-resettlement-passport-api

clamav:
  nameOverride: clamav
  resources:
    requests:
      memory: 1G
    limits:
      memory: 2G
  replicaCount: 2

gotenberg:
  nameOverride: gotenberg
  replicaCount: 2

  image:
    repository: gotenberg/gotenberg
    tag: 8.3.0
    port: 3000

  containerCommand: [ "gotenberg" ]
  containerArgs: [ "--chromium-ignore-certificate-errors","--api-timeout=30s","--pdfengines-engines=pdftk" ]

  ingress:
    enabled: false

  livenessProbe:
    httpGet:
      path: /health
    periodSeconds: 30
    initialDelaySeconds: 60
    timeoutSeconds: 20
    failureThreshold: 10

  readinessProbe:
    httpGet:
      path: /health
    periodSeconds: 20
    initialDelaySeconds: 60
    timeoutSeconds: 30
    failureThreshold: 15

  podSecurityContext:
    fsGroup: 1001

  securityContext:
    runAsUser: 1001
    privileged: false
    runAsNonRoot: true

# Whether to deploy the stubs
# Override in values-dev.yaml
# Also update the environment variables to point the application to the mocked services (on port 80) e.g. http://cvl-stub-api
deploy_stubs: false


