{{- $targetNamespace := .Release.Namespace }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
  name: {{ include "app.fullname" . }}-external-api-custom

spec:
  groups:
    - name: resettlement-passport-application-rules
      rules:
        - alert: DatabaseConnectionFailure
          expr: rate(spring_data_repository_invocations_seconds_count{exception="JDBCConnectionException", namespace="{{ $targetNamespace }}"}[1h]) > 0
          for: 5m
          labels:
            severity: {{ index .Values "generic-prometheus-alerts" "alertSeverity" }}
          annotations:
            message: Database connection failure detection - check database logs in RDS!
            runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/RR/pages/4469850163/Development+Guides
            dashboard_url: {{ $.Values.grafanaUrl }}/d/application-alerts/application-alerts?orgId=1&var-namespace={{ $targetNamespace }}
            summary: Database connection failures
        - alert: SSLCertExpiring
          expr: certmanager_certificate_expiration_timestamp_seconds{exported_namespace="{{ $targetNamespace }}"} - time() < 2505600
          for: 5m
          labels:
            severity: {{ index .Values "generic-prometheus-alerts" "alertSeverity" }}
          annotations:
            message: Service SSL Certificate is expiring in 2 weeks. It should have auto renewed.
            runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/RR/pages/5615747926/Expired+certificates
            dashboard_url: {{ $.Values.grafanaUrl }}/d/application-alerts/application-alerts?orgId=1&var-namespace={{ $targetNamespace }}
            summary: SSL Certificate is expiring in 2 weeks.