{{- $targetNamespace := .Release.Namespace }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
  name: {{ include "app.fullname" . }}-external-api-custom

spec:
  groups:
    - name: resettlement-passport-application-rules
      rules:
          - alert: ExternalAPICritical
            expr:((count by (client_name) ((rate(http_client_requests_seconds_count{namespace = "hmpps-resettlement-passport-preprod", status!~"2\\d{2}", status!="404"}[24h]))) / (count by (client_name) (rate(http_client_requests_seconds_count{namespace = "hmpps-resettlement-passport-preprod"}[24h]))))) * 100 > 5
            for: 5m
            labels:
              severity: {{ index .Values "generic-prometheus-alerts" "alertSeverity" }}
            annotations:
              message: The External API's errors for HTTP request {{ `{{` }} $labels.client_name }} got  {{ `{{` }} $labels.value}}% failures on host {{ index .Values "generic-service" "ingress" "host"}} exceeds the threshold 5%
              runbook_url: https://dsdmoj.atlassian.net/wiki/spaces/RR/pages/5119475840/External+API+Failures
              dashboard_url: {{ $.Values.grafanaUrl }}/d/application-alerts/application-alerts?orgId=1&var-namespace={{ $targetNamespace }}
              summary: External API's Failures