{{- if .Values.deploy_stubs }}
{{- $filesGlob := "files/stubs/__files/*" }}
{{- $mappingsGlob := "files/stubs/mappings/*" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hmpps-resettlement-passport-api-stub-data-files
data:
{{ ($.Files.Glob $filesGlob).AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hmpps-resettlement-passport-api-stub-data-mappings
data:
{{ ($.Files.Glob $mappingsGlob).AsConfig | indent 2 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hmpps-resettlement-passport-api-stubs
  labels:
    app.kubernetes.io/name: hmpps-resettlement-passport-api-stubs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hmpps-resettlement-passport-api-stubs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hmpps-resettlement-passport-api-stubs
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: hmpps-resettlement-passport-api-stubs
          image: wiremock/wiremock
          command: ["/docker-entrypoint.sh", "--no-request-journal", "--global-response-templating"]
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: files-volume
              mountPath: /home/wiremock/__files
            - name: mappings-volume
              mountPath: /home/wiremock/mappings
          livenessProbe:
            httpGet:
              path: /__admin/mappings
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: files-volume
          configMap:
            name: hmpps-resettlement-passport-api-stub-data-files
        - name: mappings-volume
          configMap:
            name: hmpps-resettlement-passport-api-stub-data-mappings
---
apiVersion: v1
kind: Service
metadata:
  name: hmpps-resettlement-passport-api-stubs
spec:
  selector:
    app.kubernetes.io/name: hmpps-resettlement-passport-api-stubs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
{{- end }}
