---
# Per environment values which override defaults in hmpps-resettlement-passport-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: resettlement-passport-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISON-REGISTER: http://prison-register-api-stub
    API_BASE_URL_PRISONER-SEARCH: http://prisoner-search-api-stub
    API_BASE_URL_CVL: http://cvl-api-stub
    API_BASE_URL_ARN: http://arn-api-stub
    API_BASE_URL_PRISON: http://prison-api-stub
    API_BASE_URL_CASE-NOTES: https://dev.offender-case-notes.service.justice.gov.uk
    API_BASE_URL_KEY-WORKER: http://key-worker-api-stub
    API_BASE_URL_ALLOCATION-MANAGER: http://allocation-manager-api-stub
    API_BASE_URL_RESETTLEMENT-PASSPORT-DELIUS: http://resettlement-passport-and-delius-api-stub
    API_BASE_URL_EDUCATION-EMPLOYMENT:  http://education-employment-api-stub
    API_BASE_URL_CIAG: http://ciag-api-stub
    API_BASE_URL_INTERVENTIONS-SERVICE: http://interventions-service-api-stub


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-resettlement-passport-non-prod

deploy_stubs:
  - cvl-api
  - prison-register-api
  - arn-api
  - prisoner-search-api
  - prison-api
  - key-worker-api
  - allocation-manager-api
  - resettlement-passport-and-delius-api
  - education-employment-api
  - ciag-api
  - interventions-service-api
