---
# Per environment values which override defaults in hmpps-resettlement-passport-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: resettlement-passport-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISON-REGISTER: https://prison-register-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_PRISONER-SEARCH: https://prisoner-search-preprod.prison.service.justice.gov.uk
    API_BASE_URL_CVL: https://create-and-vary-a-licence-api-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_ARN: https://assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_PRISON: https://prison-api-preprod.prison.service.justice.gov.uk
    API_BASE_URL_CASE-NOTES: https://preprod.offender-case-notes.service.justice.gov.uk
    API_BASE_URL_KEY-WORKER: https://keyworker-api-preprod.prison.service.justice.gov.uk
    API_BASE_URL_ALLOCATION-MANAGER: https://allocation-manager-preprod.apps.live.cloud-platform.service.justice.gov.uk
    API_BASE_URL_RESETTLEMENT-PASSPORT-DELIUS: https://resettlement-passport-and-delius-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_EDUCATION-EMPLOYMENT:  https://education-employment-api-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_INTERVENTIONS-SERVICE: https://hmpps-interventions-service-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
    API_BASE_URL_POP-USER-SERVICE: https://person-on-probation-user-api-preprod.hmpps.service.justice.gov.uk
    SCHEDULE_EXPRESSION_CUSTOM-METRICS: 0 0/15 * * * ?
    SCHEDULE_EXPRESSION_RELEASE-DAY-METRICS: 0 0 8 * * *
    SCHEDULE_EXPRESSION_RECONCILE-RELEASE-DATES: 0 0 2 * * *
    SCHEDULE_EXPRESSION_DELETE-EXPIRED-OTP: 0 0 3 * * *
    interventions-api-integration_crsAppointmentsEnabled: true
    SPRING_PROFILES_ACTIVE: "logstash,offender-events"

  namespace_secrets:
    sqs-prisoner-event-queue-secret:
      OFFENDER_EVENT_QUEUE_NAME: "sqs_queue_name"
      OFFENDER_EVENT_DLQ_NAME: "sqs_dlq_queue_name"


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-resettlement-passport-non-prod
