---
# Per environment values which override defaults in hmpps-resettlement-passport-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: resettlement-passport-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISON-REGISTER: http://hmpps-resettlement-passport-api-stubs/prison-register-api
    API_BASE_URL_PRISONER-SEARCH: http://hmpps-resettlement-passport-api-stubs/prisoner-search-api
    API_BASE_URL_CVL: http://hmpps-resettlement-passport-api-stubs/cvl-api
    API_BASE_URL_ARN: http://hmpps-resettlement-passport-api-stubs/arn-api
    API_BASE_URL_PRISON: http://hmpps-resettlement-passport-api-stubs/prison-api
    API_BASE_URL_CASE-NOTES: https://dev.offender-case-notes.service.justice.gov.uk
    API_BASE_URL_KEY-WORKER: http://hmpps-resettlement-passport-api-stubs/key-worker-api
    API_BASE_URL_ALLOCATION-MANAGER: http://hmpps-resettlement-passport-api-stubs/allocation-manager-api
    API_BASE_URL_RESETTLEMENT-PASSPORT-DELIUS: http://hmpps-resettlement-passport-api-stubs/resettlement-passport-and-delius-api
    API_BASE_URL_EDUCATION-EMPLOYMENT:  http://hmpps-resettlement-passport-api-stubs/education-employment-api
    API_BASE_URL_INTERVENTIONS-SERVICE: http://hmpps-resettlement-passport-api-stubs/interventions-service-api
    API_BASE_URL_POP-USER-SERVICE: https://person-on-probation-user-api-dev.hmpps.service.justice.gov.uk
    SCHEDULE_EXPRESSION_CUSTOM-METRICS: 0 0/15 * * * ?
    SCHEDULE_EXPRESSION_RELEASE-DAY-METRICS: 0 0/20 * * * ?
    SCHEDULE_EXPRESSION_RECONCILE-RELEASE-DATES: 0 0 2 * * *
    SCHEDULE_EXPRESSION_DELETE-EXPIRED-OTP: 0 0 3 * * *
    interventions-api-integration_crsAppointmentsEnabled: true
    SPRING_PROFILES_ACTIVE: "logstash,offender-events"
  
  namespace_secrets:
    sqs-prisoner-event-queue-secret:
      OFFENDER_EVENT_QUEUE_NAME: "sqs_queue_name"
      OFFENDER_EVENT_DLQ_NAME: "sqs_dlq_queue_name"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-resettlement-passport-non-prod

deploy_stubs: true
