---
# Per environment values which override defaults in hmpps-resettlement-passport-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: resettlement-passport-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISON-REGISTER: https://prison-register-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_OFFENDER-SEARCH: https://prisoner-search-preprod.prison.service.justice.gov.uk
    API_BASE_URL_CVL: https://create-and-vary-a-licence-api-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_ARN: https://assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_PRISON: https://api-preprod.prison.service.justice.gov.uk
    API_BASE_URL_OFFENDER-CASE-NOTES: https://preprod.offender-case-notes.service.justice.gov.uk
    API_BASE_URL_KEY-WORKER: https://keyworker-api-preprod.prison.service.justice.gov.uk
    API_BASE_URL_ALLOCATION-MANAGER: https://allocation-manager-preprod.apps.live.cloud-platform.service.justice.gov.uk
    API_BASE_URL_RESETTLEMENT-PASSPORT-DELIUS: https://resettlement-passport-and-delius-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_EDUCATION-EMPLOYMENT:  https://education-employment-api-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_CIAG: https://ciag-induction-api-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_INTERVENTIONS-SERVICE: https://hmpps-interventions-service-preprod.apps.live-1.cloud-platform.service.justice.gov.uk


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
