---
# Per environment values which override defaults in hmpps-resettlement-passport-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: resettlement-passport-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISON: http://prison-register-api-stub
    API_BASE_URL_OFFENDER-SEARCH: https://prisoner-offender-search-dev.prison.service.justice.gov.uk
    API_BASE_URL_CVL: http://cvl-api-stub
    API_BASE_URL_COMMUNITY: http://community-api-stub
    API_BASE_URL_ARN: http://arn-api-stub

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev

deploy_stubs:
  - cvl-api
  - community-api
  - prison-register-api
  - arn-api
