---
# Per environment values which override defaults in hmpps-resettlement-passport-api/values.yaml

generic-service:
  replicaCount: 2
  serviceAccountName: hmpps-resettlement-passport-preprod-irsa

  ingress:
    host: resettlement-passport-api-preprod.hmpps.service.justice.gov.uk

  env:
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISONER-SEARCH: https://prisoner-search-preprod.prison.service.justice.gov.uk
    API_BASE_URL_CVL: https://create-and-vary-a-licence-api-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_ARN: https://assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_PRISON: https://prison-api-preprod.prison.service.justice.gov.uk
    API_BASE_URL_CASE-NOTES: https://preprod.offender-case-notes.service.justice.gov.uk
    API_BASE_URL_KEY-WORKER: https://keyworker-api-preprod.prison.service.justice.gov.uk
    API_BASE_URL_ALLOCATION-MANAGER: https://preprod.moic.service.justice.gov.uk
    API_BASE_URL_RESETTLEMENT-PASSPORT-DELIUS: https://resettlement-passport-and-delius-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_EDUCATION-EMPLOYMENT:  https://education-employment-api-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_INTERVENTIONS-SERVICE: https://hmpps-interventions-service-preprod.apps.live-1.cloud-platform.service.justice.gov.uk
    API_BASE_URL_POP-USER-SERVICE: https://person-on-probation-user-api-preprod.hmpps.service.justice.gov.uk
    SCHEDULE_EXPRESSION_DELETE-EXPIRED-OTP: 0 0 3 * * *
    interventions-api-integration_crsAppointmentsEnabled: true
    API_BASE_URL_gotenberg-api: http://hmpps-resettlement-passport-api-gotenberg
    PSFR_BASE_URL: https://resettlement-passport-ui-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_CURIOUS_SERVICE: https://preprodservices.sequation.net
    API_BASE_URL_MANAGE_USERS_SERVICE: https://manage-users-api-preprod.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-resettlement-passport-non-prod
  businessHoursOnly: true

clamav:
  replicaCount: 1

gotenberg:
  replicaCount: 1