---
# Per environment values which override defaults in hmpps-resettlement-passport-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: resettlement-passport-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISON-REGISTER: https://prison-register-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_OFFENDER-SEARCH: https://prisoner-search-preprod.prison.service.justice.gov.uk
    API_BASE_URL_CVL: https://create-and-vary-a-licence-api-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_ARN: https://assess-risks-and-needs-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_PRISON: https://api-preprod.prison.service.justice.gov.uk
    API_BASE_URL_OFFENDER-CASE-NOTES: https://preprod.offender-case-notes.service.justice.gov.uk
    API_BASE_URL_KEY-WORKER: https://keyworker-api-preprod.prison.service.justice.gov.uk
    API_BASE_URL_ALLOCATION-MANAGER: https://allocation-manager-preprod.apps.live.cloud-platform.service.justice.gov.uk
    API_BASE_URL_RESETTLEMENT-PASSPORT-DELIUS: https://resettlement-passport-and-delius-preprod.hmpps.service.justice.gov.uk
    API_BASE_URL_INTERVENTIONS-SERVICE: https://hmpps-interventions-service-preprod.apps.live-1.cloud-platform.service.justice.gov.uk

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live-1: "35.178.209.113/32"
    cloudplatform-live-2: "3.8.51.207/32"
    cloudplatform-live-3: "35.177.252.54/32"
    cymulate-1: "54.217.50.18/32"
    cymulate-2: "52.208.202.111/32"
    cymulate-3: "52.49.144.209/32"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
