---
# Per environment values which override defaults in hmpps-resettlement-passport-api/values.yaml

generic-service:
  replicaCount: 2
  serviceAccountName: hmpps-resettlement-passport-dev-irsa

  ingress:
    host: resettlement-passport-api-dev.hmpps.service.justice.gov.uk

  env:
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISONER-SEARCH: http://hmpps-resettlement-passport-api-stubs/prisoner-search-api
    API_BASE_URL_CVL: http://hmpps-resettlement-passport-api-stubs/cvl-api
    API_BASE_URL_ARN: http://hmpps-resettlement-passport-api-stubs/arn-api
    API_BASE_URL_PRISON: http://hmpps-resettlement-passport-api-stubs/prison-api
    API_BASE_URL_CASE-NOTES: https://dev.offender-case-notes.service.justice.gov.uk
    API_BASE_URL_KEY-WORKER: http://hmpps-resettlement-passport-api-stubs/key-worker-api
    API_BASE_URL_ALLOCATION-MANAGER: http://hmpps-resettlement-passport-api-stubs/allocation-manager-api
    API_BASE_URL_RESETTLEMENT-PASSPORT-DELIUS: http://hmpps-resettlement-passport-api-stubs/resettlement-passport-and-delius-api
    API_BASE_URL_EDUCATION-EMPLOYMENT:  http://hmpps-resettlement-passport-api-stubs/education-employment-api
    API_BASE_URL_INTERVENTIONS-SERVICE: http://hmpps-resettlement-passport-api-stubs/interventions-service-api
    API_BASE_URL_POP-USER-SERVICE: https://person-on-probation-user-api-dev.hmpps.service.justice.gov.uk
    SCHEDULE_EXPRESSION_DELETE-EXPIRED-OTP: 0 0 3 * * *
    interventions-api-integration_crsAppointmentsEnabled: true
    API_BASE_URL_gotenberg-api: http://hmpps-resettlement-passport-api-gotenberg
    HMPPS_SAR_ADDITIONALACCESSROLE: "RESETTLEMENT_PASSPORT_EDIT"
    PSFR_BASE_URL: https://resettlement-passport-ui-dev.hmpps.service.justice.gov.uk
    API_BASE_URL_CURIOUS_SERVICE: http://hmpps-resettlement-passport-api-stubs/curious-api
    API_BASE_URL_MANAGE_USERS_SERVICE: https://manage-users-api-dev.hmpps.service.justice.gov.uk
    READ_ONLY_MODE_VALUE: true

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-resettlement-passport-non-prod
  businessHoursOnly: true

custom-prometheus-alerts:
  businessHoursOnly: true

deploy_stubs: true

clamav:
  replicaCount: 1

gotenberg:
  replicaCount: 1
